config/routes.rb
Rails.application.routes.draw do
  resources :fan_comments

  resources :reviews

  resources :authors

  resources :users

  resources :books, constraints: { id: /[0-9]+/ }

  get 'hello/list' => 'hello#list'
  get 'books/recent/' => 'books#recent'
  get 'books/publisher/:publisher' => 'books#publisher'

end

app/models/book.rb
class Book < ActiveRecord::Base
    validates :isbn,
        presence: true,
        uniqueness: true
    validates :title,
        presence: true,
        length: { minimum: 1, maximum: 100 },
        uniqueness: { scope: :publish }
    validates :price,
        numericality: { only_integer: true, less_than: 10000 }
    validates :publish,
        inclusion: { in: ['技術評論社', '翔泳社', '秀和システム', '日経BP社', 'ソシム'] }

    has_many :reviews
    has_and_belongs_to_many :authors
    has_many :users, through: :reviews

    scope :publisher, ->(pub) {
        where(publish: pub).order(published: :desc).limit(10)
    }
    after_destroy BookCallbacks.new
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :destroy]
  
  # GET /books
  # GET /books.json
  def index
      @books = Book.includes(:authors).all
      logger.info session[:site_access_counter]
  end

  def recent
      two_years_ago = (Time.now - 2 * 365 * 86400).strftime('%Y-%m-%d')
      @books = Book.where('published > ?', two_years_ago).order(published: :desc)
  end

  def publisher
      @books = Book.publisher(params[:publisher])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    Book.transaction(isolation: :repeatable_read) do
        @book = Book.find(params[:id])
        respond_to do |format|
          if @book.update(book_params)
            format.html { redirect_to @book, notice: 'Book was successfully updated.' }
            format.json { render :show, status: :ok, location: @book }
          else
            format.html { render :edit }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end
    end
  rescue => e
      render text: e.message
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn, :title, :price, :publish, :published, :cd, :lock_version)
    end
end

app/helpers/books_helper.rb
module BooksHelper
    def list_tag(collection, prop)
        content_tag(:ul) do
            collection.each do |element|
                concat content_tag(:li, element.attributes[prop])
            end
        end
    end
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :publish %><br>
    <%= f.text_field :publish %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.date_select :published %>
  </div>
  <div class="field">
    <%= f.label :cd %><br>
    <%= f.check_box :cd %>
  </div>
  <%= f.hidden_field :lock_version %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_table.html.erb
<%- unless @books.empty? %>
<table>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Price</th>
      <th>Publish</th>
      <th>Published</th>
      <th>Cd</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.price %></td>
        <td><%= book.publish %></td>
        <td><%= book.published %></td>
        <td><%= book.cd %></td>
        <td><%= book.authors.map{|author| author.name }.join(%q|,|) %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%- end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Price</th>
      <th>Publish</th>
      <th>Published</th>
      <th>Cd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.price %></td>
        <td><%= book.publish %></td>
        <td><%= book.published %></td>
        <td><%= book.cd %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/publisher.html.erb
<h1>Listing books</h1>

<summary>count:<%= @books.count %></summary>
<%= render 'table', books: @books %>

<br>

<%= link_to 'New Book', new_book_path %>
<%= link_to 'All Books', books_path %>

app/views/books/recent.html.erb
<h1>Listing books</h1>

<%= render 'table', books: @books %>

<br>

<%= link_to 'New Book', new_book_path %>
<%= link_to 'All Books', books_path %>

<%= list_tag(@books, 'title') %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @book.publish %>
</p>

<p>
  <strong>Published:</strong>
  <%= @book.published %>
</p>

<p>
  <strong>Cd:</strong>
  <%= @book.cd %>
</p>

<p>
  <strong>Reviews:</strong>
<% unless @book.reviews.empty? %>
</p>
<ul>
    <% @book.reviews.each do |review| %>
        <li><%= review.body %></li>
    <% end %>
</ul>
<% end %>

<p>
  <strong>Authors:</strong>
<% unless @book.authors.empty? %>
</p>
<ul>
    <% @book.authors.each do |author| %>
        <li><%= link_to author.name, user_path(author.user_id) %></li>
    <% end %>
</ul>
<% end %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>